#!/usr/bin/env bash
# Verification gate (cursor-quality-kit, Expo / EAS + Neon).
# Stages 1-4 of .ai/ACCEPTANCE.md. A task is done only when this exits 0.
# Agents must not edit this file to skip checks.
#
# Optional environment:
#   VERIFY_SKIP_DOCTOR=1   skip expo-doctor (needs network)
#   VERIFY_COVERAGE=1      run Jest with coverage (thresholds come from jest config)
#   VERIFY_BUILD=0|1       bundle the iOS app with `expo export` (default: 1 in CI, 0 locally)
#   VERIFY_E2E=1           run Maestro flows against an already running iOS simulator build
set -euo pipefail
cd "$(dirname "$0")/.."

step() { printf '\n==> %s\n' "$*"; }
has_dep() {
  node -e "const p=require('./package.json');process.exit({...p.dependencies,...p.devDependencies}[process.argv[1]]?0:1)" "$1"
}
in_ci() { [ -n "${CI:-}" ] && [ "${CI}" != "0" ] && [ "${CI}" != "false" ]; }

step "Regression guard"
./.ai/bin/guard.sh --worktree

step "Dependencies match the Expo SDK"
CI=1 npx expo install --check

if [ "${VERIFY_SKIP_DOCTOR:-0}" != "1" ]; then
  step "expo-doctor"
  CI=1 npx --yes expo-doctor@latest
fi

# Stage 1: types
if has_dep prettier; then
  step "Formatting (prettier)"
  npx prettier --check .
fi

step "Lint (eslint, zero warnings)"
npx eslint . --max-warnings=0

step "TypeScript strict mode is on"
npx tsc --showConfig | node -e '
  let s = ""; process.stdin.on("data", (d) => (s += d)).on("end", () => {
    const strict = JSON.parse(s).compilerOptions?.strict === true;
    if (!strict) { console.error("verify: tsconfig.json must keep \"strict\": true"); process.exit(1); }
  });'

step "Typecheck (tsc)"
# expo-env.d.ts is generated by `expo start` and git-ignored, so clean checkouts (CI) lack it.
if [ ! -f expo-env.d.ts ] && grep -q 'expo-env.d.ts' tsconfig.json 2>/dev/null; then
  printf '/// <reference types="expo/types" />\n\n// NOTE: This file should not be edited and should be in your git ignore' >expo-env.d.ts
fi
npx tsc --noEmit

# Stage 2: tests
step "Unit and component tests (jest)"
if [ "${VERIFY_COVERAGE:-0}" = "1" ]; then
  npx jest --ci --coverage
else
  npx jest --ci
fi

if has_dep drizzle-kit && ls drizzle.config.* >/dev/null 2>&1; then
  step "Drizzle migrations consistency"
  npx drizzle-kit check
fi

# Stage 3: builds
build_default=0
in_ci && build_default=1
if [ "${VERIFY_BUILD:-$build_default}" = "1" ]; then
  step "Build: iOS JavaScript bundle (expo export)"
  out="$(mktemp -d)"
  npx expo export --platform ios --output-dir "$out"
  rm -rf "$out"
fi

# Stage 4: E2E (needs Maestro and a booted simulator with the app installed)
if [ "${VERIFY_E2E:-0}" = "1" ]; then
  step "E2E (maestro)"
  command -v maestro >/dev/null || { echo "verify: VERIFY_E2E=1 but maestro is not installed" >&2; exit 1; }
  maestro test .maestro/
fi

printf '\nverify: OK\n'
