#!/usr/bin/env bash
# Verification gate (cursor-quality-kit, Expo / EAS + Neon).
# A task is done only when this exits 0. Agents must not edit this file to skip checks.
#
# Optional environment:
#   VERIFY_SKIP_DOCTOR=1   skip expo-doctor (needs network)
#   VERIFY_COVERAGE=1      run Jest with coverage (thresholds come from jest config)
set -euo pipefail
cd "$(dirname "$0")/.."

step() { printf '\n==> %s\n' "$*"; }
has_dep() {
  node -e "const p=require('./package.json');process.exit({...p.dependencies,...p.devDependencies}[process.argv[1]]?0:1)" "$1"
}

step "Regression guard"
./.ai/bin/guard.sh --worktree

step "Dependencies match the Expo SDK"
CI=1 npx expo install --check

if [ "${VERIFY_SKIP_DOCTOR:-0}" != "1" ]; then
  step "expo-doctor"
  CI=1 npx --yes expo-doctor@latest
fi

if has_dep prettier; then
  step "Formatting (prettier)"
  npx prettier --check .
fi

step "Lint (eslint, zero warnings)"
npx eslint . --max-warnings=0

step "Typecheck (tsc)"
# expo-env.d.ts is generated by `expo start` and git-ignored, so clean checkouts (CI) lack it.
if [ ! -f expo-env.d.ts ] && grep -q 'expo-env.d.ts' tsconfig.json 2>/dev/null; then
  printf '/// <reference types="expo/types" />\n\n// NOTE: This file should not be edited and should be in your git ignore' >expo-env.d.ts
fi
npx tsc --noEmit

step "Unit and component tests (jest)"
if [ "${VERIFY_COVERAGE:-0}" = "1" ]; then
  npx jest --ci --coverage
else
  npx jest --ci
fi

if has_dep drizzle-kit && ls drizzle.config.* >/dev/null 2>&1; then
  step "Drizzle migrations consistency"
  npx drizzle-kit check
fi

printf '\nverify: OK\n'
