#!/usr/bin/env bash
# Install this kit into the repositories listed in rollout/ and open one pull request per repository.
#
# Usage:
#   scripts/rollout.sh [--dry-run] [--work <dir>] [owner/name ...]
#
# Each repository has rollout/<owner>__<name>.conf with `stack=`, optional `options=` (extra
# install.sh options) and `verify=` (project checks for a new scripts/verify.sh). Optional
# rollout/<owner>__<name>.remove lists paths the kit supersedes (deleted in the same pull request)
# and rollout/<owner>__<name>.md is added to the pull request description.
# The branch quality-kit/install is rebuilt from the default branch on every run and force-pushed,
# so the pull request always shows exactly what this kit version installs. Needs `gh` and git
# access to the repositories. --dry-run commits locally and prints the change instead of pushing.
set -euo pipefail

usage() { sed -n '3,14p' "$0" | sed 's/^# \{0,1\}//'; }

KIT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
VERSION="$(tr -d '[:space:]' <"$KIT_DIR/VERSION")"
BRANCH="quality-kit/install"
dry=0
work=""
repos=()
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) dry=1 ;;
    --work) work="${2:?--work needs a directory}"; shift ;;
    -h|--help) usage; exit 0 ;;
    -*) echo "rollout: unknown option $1" >&2; usage >&2; exit 2 ;;
    *) repos+=("$1") ;;
  esac
  shift
done
if [ "${#repos[@]}" -eq 0 ]; then
  for c in "$KIT_DIR"/rollout/*.conf; do
    [ -f "$c" ] || continue
    c="$(basename "$c" .conf)"
    repos+=("${c%%__*}/${c#*__}")
  done
fi
[ "${#repos[@]}" -gt 0 ] || { echo "rollout: no repositories in $KIT_DIR/rollout" >&2; exit 2; }
[ -n "$work" ] || work="$(mktemp -d)"
mkdir -p "$work"
kit_commit="$(git -C "$KIT_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"

conf_get() { sed -n "s/^$1=//p" "$2" | tail -n 1; }

# clone_url <owner/name>: overridable for tests (ROLLOUT_REMOTE_BASE=/path/to/bare/repos).
clone_url() { printf '%s/%s.git\n' "${ROLLOUT_REMOTE_BASE:-https://github.com}" "$1"; }

failed=0
for repo in "${repos[@]}"; do
  base="$KIT_DIR/rollout/${repo//\//__}"
  conf="$base.conf"
  echo "== $repo"
  [ -f "$conf" ] || { echo "rollout: $conf is missing" >&2; failed=1; continue; }
  stack="$(conf_get stack "$conf")"
  options="$(conf_get options "$conf")"
  verify="$(conf_get verify "$conf")"
  dir="$work/${repo//\//__}"
  rm -rf "$dir"
  git clone -q --depth 1 "$(clone_url "$repo")" "$dir"
  default="$(git -C "$dir" rev-parse --abbrev-ref HEAD)"
  git -C "$dir" checkout -q -B "$BRANCH"

  removed=""
  if [ -f "$base.remove" ]; then
    while IFS= read -r p; do
      case "$p" in ''|'#'*) continue ;; esac
      if [ -e "$dir/$p" ] || [ -L "$dir/$p" ]; then
        git -C "$dir" rm -r -q -- "$p"
        removed="$removed- \`$p\`
"
      fi
    done <"$base.remove"
  fi

  args=(--no-hooks --stack "$stack")
  # shellcheck disable=SC2206 # options are whitespace-separated install.sh flags
  [ -n "$options" ] && args+=($options)
  [ -n "$verify" ] && args+=(--verify-cmd "$verify")
  if ! "$KIT_DIR/scripts/install.sh" "${args[@]}" "$dir" >"$work/install.log" 2>&1; then
    echo "rollout: install.sh failed for $repo:" >&2
    sed 's/^/  /' "$work/install.log" >&2
    failed=1
    continue
  fi

  git -C "$dir" add -A
  if git -C "$dir" diff --cached --quiet; then
    echo "rollout: $repo already has kit $VERSION; nothing to do"
    continue
  fi
  git -C "$dir" -c user.name="${ROLLOUT_GIT_NAME:-quality-kit-rollout}" \
    -c user.email="${ROLLOUT_GIT_EMAIL:-41898282+github-actions[bot]@users.noreply.github.com}" \
    commit -q --no-verify -m "Install cursor-quality-kit $VERSION" -m "Generated by scripts/rollout.sh from the kit at $kit_commit."

  body="$work/body.md"
  {
    echo "Installs [cursor-quality-kit](https://github.com/${KIT_REPO:-alemmle/cursor-quality-kit}) $VERSION (kit commit \`$kit_commit\`) with \`--stack $stack${options:+ $options}\`."
    echo
    echo "This branch is generated by the kit's rollout workflow and rebuilt from \`$default\` on every run, so do not push to it. Change the kit or \`rollout/${repo//\//__}.*\` there instead, and do follow-up work in a separate pull request after this one merges."
    echo
    echo "### Before merging"
    echo
    echo "- [ ] The kit's \`main\` branch contains this kit version, because CI here calls the kit's reusable workflows at \`main\`."
    echo "- [ ] Reviewed the diff, then added the \`ai-gate-change-approved\` label. The guard blocks gate files (\`.ai/\`, \`scripts/verify.sh\`, workflows, hook configs) without it."
    echo "- [ ] \`./scripts/verify.sh\` passes on this branch."
    echo
    echo "After merging, run \`git config core.hooksPath .githooks\` once in each clone. That is local git config, so a pull request cannot set it."
    if [ -n "$removed" ]; then
      echo
      echo "### Removed because the kit now covers it"
      echo
      printf '%s' "$removed"
    fi
    if grep -qE '^  (warn|pending) ' "$work/install.log"; then
      echo
      echo "### Installer notes"
      echo
      grep -E '^  (warn|pending) ' "$work/install.log" | sed -E 's/^  (warn|pending) +/- /'
    fi
    if [ -f "$base.md" ]; then
      echo
      cat "$base.md"
    fi
    echo
    echo "<details><summary>Installer output</summary>"
    echo
    echo '```text'
    cat "$work/install.log"
    echo '```'
    echo "</details>"
  } >"$body"

  if [ "$dry" = 1 ]; then
    git -C "$dir" --no-pager show --stat --format='%s' HEAD | tail -n 3
    echo "rollout: dry run; pull request body in $body"
    cp "$body" "$work/${repo//\//__}.body.md"
    continue
  fi

  git -C "$dir" push -q --force origin "$BRANCH"
  title="Install cursor-quality-kit $VERSION"
  number="$(gh pr list -R "$repo" --head "$BRANCH" --state open --json number --jq '.[0].number // empty')"
  if [ -n "$number" ]; then
    gh pr edit "$number" -R "$repo" --title "$title" --body-file "$body" >/dev/null
    echo "rollout: updated $repo#$number"
  else
    gh pr create -R "$repo" --draft --base "$default" --head "$BRANCH" --title "$title" --body-file "$body"
  fi
done
exit "$failed"
